allow_reboot: true
manage_firewall: true
manage_network: false
network_type: static
locale_default: en_US.UTF-8

packages:
  - apache2-utils
  - cryptsetup
  - curl
  - dnsutils
  - hashdeep
  - htop
  - jq
  - kpartx
  - ncdu
  - rsync
  - screen
  - strace
  - tree
  - vim
  - wget


base_scripts: /srv/.scripts
