base_allow_reboot: true
base_manage_firewall: true
base_manage_network: false
base_network_type: static
base_locale_default: en_US.UTF-8

base_packages:
  - apache2-utils
  - cryptsetup
  - curl
  - dnsutils
  - hashdeep
  - htop
  - jq
  - kpartx
  - ncdu
  - rsync
  - screen
  - strace
  - tree
  - vim
  - wget


base_scripts: /srv/.scripts
base_ssh_ufw_rule: limit
